### PR TITLE
Add book Info page

### PR DESCRIPTION
**Pull request by angie4u**
# Scenario
If user click one of book from the list -> it will route to this '/bookinfo' page which provides brief information of the book. If a user clicks 'start reading' button, then it will routes to Epub reader page("/book").

# Screenshot
image

## After click **Start Reading** button
image

### CODE REVIEW

**Comment by ljh95** [comment]
very Good

**Comment by ljh95** [comment]
good i checked

**Review by ljh95 — COMMENTED** [review]
확인했습니다.

**Review by ljh95 — COMMENTED** [review]
전부 확인했습니다.

**Comment by angie4u** [comment]
@ljh95 다시 Approve 부탁 드려요! 지난번 PR이 master브랜치에 제대로 merge되지 않은 것 같아요

**Review by ljh95 — APPROVED** [review]
확인했습니다.

**Pull request merged**
